import Foundation

struct ProductDisplayNameProvider {
    private static let seededProductKeys: [String: String] = [
        "milk": "product.milk",
        "bread": "product.bread",
        "eggs": "product.eggs",
        "cheese": "product.cheese",
        "butter": "product.butter",
        "yogurt": "product.yogurt",
        "water": "product.water",
        "salt": "product.salt",
        "olive oil": "product.olive_oil",
        "tomatoes": "product.tomatoes",
        "potatoes": "product.potatoes",
        "carrots": "product.carrots",
        "cucumber": "product.cucumber",
        "lettuce": "product.lettuce",
        "broccoli": "product.broccoli",
        "peppers": "product.peppers",
        "onions": "product.onions",
        "garlic": "product.garlic",
        "mushrooms": "product.mushrooms",
        "avocado": "product.avocado",
        "apples": "product.apples",
        "bananas": "product.bananas",
        "grapes": "product.grapes",
        "orange": "product.orange",
        "lemon": "product.lemon",
        "strawberries": "product.strawberries",
        "chicken": "product.chicken",
        "ground meat": "product.ground_meat",
        "fish": "product.fish",
        "tuna": "product.tuna",
        "bacon": "product.bacon",
        "beans": "product.beans",
        "lentils": "product.lentils",
        "nuts": "product.nuts",
        "rice": "product.rice",
        "pasta": "product.pasta",
        "flour": "product.flour",
        "sugar": "product.sugar",
        "coffee": "product.coffee",
        "tea": "product.tea",
        "cereal": "product.cereal",
        "biscuits": "product.biscuits",
        "breadsticks": "product.breadsticks",
        "honey": "product.honey",
        "jam": "product.jam",
        "tomato sauce": "product.tomato_sauce",
        "frozen vegetables": "product.frozen_vegetables",
        "frozen pizza": "product.frozen_pizza",
        "frozen fish": "product.frozen_fish",
        "ice cream": "product.ice_cream",
        "sparkling water": "product.sparkling_water",
        "juice": "product.juice",
        "soda": "product.soda",
        "beer": "product.beer",
        "wine": "product.wine",
        "dish soap": "product.dish_soap",
        "laundry detergent": "product.laundry_detergent",
        "fabric softener": "product.fabric_softener",
        "bleach": "product.bleach",
        "multi-surface cleaner": "product.multi_surface_cleaner",
        "glass cleaner": "product.glass_cleaner",
        "sponges": "product.sponges",
        "trash bags": "product.trash_bags",
        "paper towels": "product.paper_towels",
        "toilet paper": "product.toilet_paper",
        "tissues": "product.tissues",
        "hand soap": "product.hand_soap",
        "shampoo": "product.shampoo",
        "toothpaste": "product.toothpaste",
        "aluminum foil": "product.aluminum_foil",
        "baking paper": "product.baking_paper",
        "chocolate": "product.chocolate",
        "cookies": "product.cookies",
        "chips": "product.chips",
        "popcorn": "product.popcorn",
        "croissant": "product.croissant",
        "bagel": "product.bagel",
        "waffle": "product.waffle",
        "pancakes": "product.pancakes",
        "cupcake": "product.cupcake",
        "cake": "product.cake",
        "pie": "product.pie",
        "doughnut": "product.doughnut",
        "coconut": "product.coconut",
        "kiwi": "product.kiwi"
    ]

    static func displayName(for canonicalName: String) -> String {
        let normalizedName = canonicalName.lowercased()
        guard let key = seededProductKeys[normalizedName] else { return canonicalName }
        return String(localized: String.LocalizationValue(key))
    }
}
